git:
  pagers:
    - pager: delta --dark --true-color=always --paging=never --line-numbers --syntax-theme "Catppuccin Mocha"
  paging:
    colorArg: always
    pager: delta --dark --true-color=always --paging=never --line-numbers --syntax-theme "Catppuccin Mocha"
